### ISSUE TITLE
crypto.randomUUID not found

### ISSUE THREAD

**Issue by phken91** [shlinkio/shlink-web-client#1325]
### shlink-web-client version

4.2.0

### How do you use shlink-web-client

selfhosted with docker

### Current behavior

fresh setup with docker, use without predefined server, and try to add server, then get this error in browser console.
`index-5ZKpCTif.js:735 TypeError: crypto.randomUUID is not a function`

### Expected behavior

add server without issues

### Minimum steps to reproduce

part of my docker compose:
```yaml
 shlink-admin:
    image: shlinkio/shlink-web-client
    environment:
      - VIRTUAL_HOST=host
      - LETSENCRYPT_HOST=host
```
