### ISSUE TITLE
How to use this docker with a reverse proxy?

### ISSUE THREAD

**Issue by Nottt** [shlinkio/shlink-web-client#141]
I'm trying to use shlink, with jwilder/nginx-proxy so I can run the web interface using my own domain.

I can access the web interface, and even create a server but nothing works.

Does this image depends on the other shlink docker? I found the wiki a little confusing in how to use the dockers.

This is my yaml file:

```
---
- name: Stop and remove any existing containers
  docker_container: "name={{ item }} state=absent"
  with_items:
    - shlink
    - shlink-web

- name: Create and start shlink container
  docker_container:
    name: shlink
    image: "shlinkio/shlink"
    pull: yes
    env:
      SHORT_DOMAIN_HOST: s.domain.com
      SHORT_DOMAIN_SCHEMA: http
      DB_DRIVER: mysql
      DB_HOST: mariadb:3306
      DB_USER: root
      DB_PASSWORD: password321
      VIRTUAL_HOST: "s.domain.com"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "s.domain.com"
      LETSENCRYPT_EMAIL: "{{ email }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - shlink
    purge_networks: yes
    restart_policy: always
    state: started
   
- name: Create and start shlink-web container
  docker_container:
    name: shlink-web
    image: "shlinkio/shlink-web-client"
    pull: yes
    env:
      VIRTUAL_HOST: "e.domain.com"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "e.domain.com"
      LETSENCRYPT_EMAIL: "{{ email }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - shlink-web
    purge_networks: yes
    restart_policy: always
    state: started
```

If I access the e.domain.com I see the web interface, so it seems fine, if I go to s.domain.com, I see this:

![image](https://user-images.githubusercontent.com/13532436/61177556-fda74080-a5ae-11e9-9266-92bf98feb6ae.png)

So both dockers seem to be working as expected, yet I can't use it?
