### ISSUE TITLE
400 Bad Request for each static source in docker image

### ISSUE THREAD

**Issue by gradano-c4w** [shlinkio/shlink-web-client#323]
#### Shlink web client version

* Version: 2.6.0
* Docker-Image

#### Summary

deploying the shlink-web-client docker image on hostname admin.XXX.co when I try to navigate to admin.XXX.co I get 
200 on http://admin.XXX.co 
400 on http://admin.XXX.co/static/css/2.47ebfb1b.chunk.css
400 on http://admin.XXX.co/static/css/main.b6e4718d.chunk.css
400 on all the static files
and I'm not able to see the web interface of the client.

I haven't problem if I try to reach the client using the public ip address of the server instead of hostname.

Are there some configuration i'm missing when I use the hostname?

this is the docker-compose configuration:

```
version: '2'
services:
  shlink-web-client:
    image: shlinkio/shlink-web-client:2.6.0
    labels:
      SERVICE_80_NAME: "shlink-admin"
      SERVICE_80_CHECK_HTTP: "/"
      SERVICE_80_TAGS: 'urlprefix-admin.XXX.co/  strip=/
    ports:
     - "80"
```

where the SERVICE_80_TAGS are the labels needed to deploy the service on our public loadbalancer.
